import * as Cesium from "cesium";

type ViewerOptions = {
    animation?: boolean;
    baseLayerPicker?: boolean;
    fullscreenButton?: boolean;
    vrButton?: boolean;
    geocoder?: boolean | Cesium.GeocoderService[];
    homeButton?: boolean;
    infoBox?: boolean;
    sceneModePicker?: boolean;
    selectionIndicator?: boolean;
    timeline?: boolean;
    navigationHelpButton?: boolean;
    navigationInstructionsInitiallyVisible?: boolean;
    scene3DOnly?: boolean;
    shouldAnimate?: boolean;
    clockViewModel?: Cesium.ClockViewModel;
    selectedImageryProviderViewModel?: Cesium.ProviderViewModel;
    imageryProviderViewModels?: Cesium.ProviderViewModel[];
    selectedTerrainProviderViewModel?: Cesium.ProviderViewModel;
    terrainProviderViewModels?: Cesium.ProviderViewModel[];
    // imageryProvider?: Cesium.ImageryProvider;
    // terrainProvider?: Cesium.TerrainProvider;
    skyBox?: Cesium.SkyBox | false;
    skyAtmosphere?: Cesium.SkyAtmosphere | false;
    // fullscreenElement?: Element | string;
    useDefaultRenderLoop?: boolean;
    targetFrameRate?: number;
    showRenderLoopErrors?: boolean;
    useBrowserRecommendedResolution?: boolean;
    automaticallyTrackDataSourceClocks?: boolean;
    contextOptions?: any;
    sceneMode?: Cesium.SceneMode;
    mapProjection?: Cesium.MapProjection;
    // globe?: Cesium.Globe | false;
    orderIndependentTranslucency?: boolean;
    // creditContainer?: Element | string;
    // creditViewport?: Element | string;
    // dataSources?: DataSourceCollection;
    shadows?: boolean;
    terrainShadows?: Cesium.ShadowMode;
    mapMode2D?: Cesium.MapMode2D;
    projectionPicker?: boolean;
    requestRenderMode?: boolean;
    maximumRenderTimeChange?: number;
};